### ISSUE TITLE
Implementation of dependencies

### ISSUE THREAD

**Issue by jpmacveigh** [difu/eccodes-lambda#1]
Hello difu
What do you mean by :
"Implement your lambda function in the lambda/ folder and install all dependencies in here" ?
Thank's

**Comment by difu** [comment]
Hi,
If you need additional Python packages you must install them into the lambda/ folder (that contains lambda_function.py.example).
All dependencies must be in that folder, no packages from e.g. site-packages will be copied into the deployment package.

for example:

```
cd lambda
pip3 install my_needed_package -t .
```

Hope this helps, if not I´d be happy to help you further!

Cheers
Dirk

**Comment by jpmacveigh** [comment]
Hi Dirk,
Thank you for your helpfull awnser.
The lambda.zip provided file is OK to deploy the lambda_function.py function as a AWS Lambda Function.
But I would like to deploy the lambda.zip file as a AWS  Lambda Layer in order to make Eccodes package usable by others functions.
Do you know how to manage this ?
Cheers
Jean Pierre

**Comment by difu** [comment]
Hi Jean Pierre,
I think you can leave the lambda folder empty, in case you just want to have eccodes as a layer. Create the deployment package and deploy it as a layer.

In your lambda function that uses that layer you should be able to import eccodes as usual

```
from eccodes import *
```

In some other projects I had to append /opt to the search path

```
import sys
sys.path.append("/opt/")
```

If this does not work let me know.

Cheers
Dirk

**Comment by jpmacveigh** [comment]
Hi Dirk,
Great ! It's OK !
I just deployed lambda.zip as a Lambda Layer
an added in my function :
import sys
sys.path.append("/opt/")

I also had to set in the Lambda environnement : 
ECCODES_DEFINITION_PATH = /opt/definitions

Thanks a lot
Jean Pierre

**Comment by difu** [comment]
Great, have fun with it!

Dirk

**Comment by jpmacveigh** [comment]
Hi Dirk,
I also had to add : 

    openjpeg2-tools \
    openjpeg2-devel \ 
    openjpeg2 \
    jasper-devel \
    jasper-libs \

to the command : RUN yum -y install

in order to make JPEG fonctionality enabled in Eccodes.
See: https://confluence.ecmwf.int/display/UDOC/JPEG+support+not+enabled%2C+cannot+decode+values%3A+Functionality+not+enabled+-+ecCodes+GRIB+FAQ

Jean Pierre

**Comment by difu** [comment]
Hi Jean Pierre,

thanks for this hint. Do you want to make a pull request?
If not I will add this next week.

Cheers Dirk

**Comment by jpmacveigh** [comment]
Dirk,
I am not enough confortable with Github to do it.
I préfere you do so.
Cheers

**Comment by difu** [comment]
Hi Jean Pierre,

I updated your request, but I didn´t test it as a layer. Please give me feedback, if it works.

Cheers Dirk

**Comment by jpmacveigh** [comment]
Hi Dirk,
Thank you.
Deployed as a layer, the producted file lambda.zip works very well.
Cheers JP
